spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyDB
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-version: 1.0.0
    baseline-on-migrate: true
       
  session:
    store-type: jdbc
    jdbc.initialize-schema: embedded
    jdbc.table-name: SPRING_SESSION

server:
  servlet:
      session.timeout: 30m